### ISSUE TITLE
pb when testing aws-sdk via npm run test

### ISSUE THREAD

**Issue by philippefuentes** [irvinlim/es2017-lambda-boilerplate#32] opened 2018-04-02 11:21 UTC
Hi Irvin,

I'm having troubles when testing via "npm run test" (docker-lambda)
I'm trying to return the aws ecs cluster list of my aws account/region, which contains 1 cluster.
but when displaying the cluster list returned by:

```
const ECS = new AWS.ECS();
var listClusters = await ECS.listClusters().promise();
console.log("PF cluster list: " + util.inspect(listClusters, false, null));
```
I get an empty list:

```
START RequestId: e2253bfa-dd82-13ca-7600-1290dc20ae81 Version: $LATEST
2018-04-02T11:06:19.472Z	e2253bfa-dd82-13ca-7600-1290dc20ae81	Event type: aws-ecs-example
2018-04-02T11:06:20.368Z	e2253bfa-dd82-13ca-7600-1290dc20ae81	PF cluster list: { clusterArns: [] }
```

When I check directely via aws cli, my cluster is returned correctly

```
11:52 $ aws ecs list-clusters --profile vetup-prod-user-terraform --region eu-west-1
{
    "clusterArns": [
        "arn:aws:ecs:eu-west-1:xxxxxxxxx:cluster/vma-cluster"
    ]
}
```

Note: My .env file contains the same credential refering by the above "vetup-prod-user-terraform" aws profile:

.env:
```
AWS_ACCESS_KEY_ID=xxxxxxxx
AWS_SECRET_ACCESS_KEY=xxxxxxxxx
AWS_REGION=eu-west-1
```

When I execute the lambda directly via aws lambda dashboard, the cluster is also correctly returned (specified the correct lambda "ecs:ListClusters" policy before):

```
START RequestId: caea0b50-3666-11e8-8584-d19946e08f2c Version: $LATEST
2018-04-02T11:12:55.583Z	caea0b50-3666-11e8-8584-d19946e08f2c	Event type: aws-ecs-example
2018-04-02T11:12:55.825Z	caea0b50-3666-11e8-8584-d19946e08f2c	PF cluster list: { clusterArns: [ 'arn:aws:ecs:eu-west-1:xxxxxxxxxxx:cluster/vma-cluster' ] }
```

Any idea what I'm missing ?
Thanks you

**Comment by irvinlim** [comment] 2018-04-02 11:27
I believe you need to set the region in the AWS SDK using `AWS.config.update({ region: process.env.AWS_REGION })`. Could you try that and let me know if it works?

The reason why it's not automatically populated is because the environment variable is only used to specify the region that the Lambda function should reside in, rather than to assume the region with the use of the AWS SDK.

I should probably rename the environment variable, since it seems like it's causing confusion.

**Comment by philippefuentes** [comment] 2018-04-02 12:01
Thank you, it was exactly that, worked with this: 

```js
AWS.config.update({ region: 'eu-west-1' });
```

Quite confusing to me indeed since process.env.AWS_REGION gave me "us-east-1", where is it defined ? dunno where it came from.
Yes, maybe the AWS_REGION var in .env should be called AWS_LAMBDA_REGION.

I guess I have to set the right aws-sdk region in the test function since it's not needed when the lambda is executed in aws.

**Comment by irvinlim** [comment] 2018-04-02 12:19
There are actually a few region settings that are possible:

1. Deployment target region
  - Uses `AWS_LAMBDA` environment variable when using `npm run deploy`
2. Local testing environment region
3. CI testing environment region
4. Production environment region

I'm thinking that for (1), since it's only for local deployment (rather than from CI) it should be called `AWS_LAMBDA_DEPLOYMENT_REGION`, along with a prompt when running the script.

For (2) and (3), the regions should be populated with an environment variable (preferably called `AWS_SDK_REGION`), while for (4) it automatically defaults to the region that the Lambda function resides in. It can also default to the environment variable if defined.

Not everyone is using this boilerplate with the AWS SDK, since it was intended as a general purpose Node.js boilerplate. I'll keep this in mind, though it feels a little out of scope at this point.

---

I'm also thinking of revising the scope of this project sometime soon, ever since learning about the [Serverless](https://github.com/serverless/serverless) framework, which essentially solves most of the problems that this project does. Hence I might just remove that deployment script in favour of Serverless' multi-platform deployment capabilities.

**Comment by philippefuentes** [comment] 2018-04-02 12:29
Thank you for your help Irvin,
Looking forward to trying your next work on the Serverless framework, sounds really cool  !

**Comment by irvinlim** [comment] 2018-04-02 12:30
No problem, glad to be of help!

I'll leave this issue open for me to remind myself next time.

**Closed** 2018-09-16 08:52 UTC
Labels: question
